// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.0
// source: internal/proto/grpcrcon/grpcrcon.proto

package grpcrcon

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResponseStatus int32

const (
	ResponseStatus_ERROR   ResponseStatus = 0
	ResponseStatus_SUCCESS ResponseStatus = 1
)

// Enum value maps for ResponseStatus.
var (
	ResponseStatus_name = map[int32]string{
		0: "ERROR",
		1: "SUCCESS",
	}
	ResponseStatus_value = map[string]int32{
		"ERROR":   0,
		"SUCCESS": 1,
	}
)

func (x ResponseStatus) Enum() *ResponseStatus {
	p := new(ResponseStatus)
	*p = x
	return p
}

func (x ResponseStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResponseStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_proto_grpcrcon_grpcrcon_proto_enumTypes[0].Descriptor()
}

func (ResponseStatus) Type() protoreflect.EnumType {
	return &file_internal_proto_grpcrcon_grpcrcon_proto_enumTypes[0]
}

func (x ResponseStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResponseStatus.Descriptor instead.
func (ResponseStatus) EnumDescriptor() ([]byte, []int) {
	return file_internal_proto_grpcrcon_grpcrcon_proto_rawDescGZIP(), []int{0}
}

type LockRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServerName string `protobuf:"bytes,1,opt,name=serverName,proto3" json:"serverName,omitempty"`
}

func (x *LockRequest) Reset() {
	*x = LockRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_grpcrcon_grpcrcon_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockRequest) ProtoMessage() {}

func (x *LockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_grpcrcon_grpcrcon_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockRequest.ProtoReflect.Descriptor instead.
func (*LockRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_grpcrcon_grpcrcon_proto_rawDescGZIP(), []int{0}
}

func (x *LockRequest) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

type UnlockRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServerName string `protobuf:"bytes,1,opt,name=serverName,proto3" json:"serverName,omitempty"`
}

func (x *UnlockRequest) Reset() {
	*x = UnlockRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_grpcrcon_grpcrcon_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnlockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlockRequest) ProtoMessage() {}

func (x *UnlockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_grpcrcon_grpcrcon_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlockRequest.ProtoReflect.Descriptor instead.
func (*UnlockRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_grpcrcon_grpcrcon_proto_rawDescGZIP(), []int{1}
}

func (x *UnlockRequest) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

type ShutdownRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServerName string `protobuf:"bytes,1,opt,name=serverName,proto3" json:"serverName,omitempty"`
}

func (x *ShutdownRequest) Reset() {
	*x = ShutdownRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_grpcrcon_grpcrcon_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShutdownRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownRequest) ProtoMessage() {}

func (x *ShutdownRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_grpcrcon_grpcrcon_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownRequest.ProtoReflect.Descriptor instead.
func (*ShutdownRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_grpcrcon_grpcrcon_proto_rawDescGZIP(), []int{2}
}

func (x *ShutdownRequest) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

type KickRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServerName string `protobuf:"bytes,1,opt,name=serverName,proto3" json:"serverName,omitempty"`
	PlayerId   string `protobuf:"bytes,2,opt,name=playerId,proto3" json:"playerId,omitempty"`
	Message    string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *KickRequest) Reset() {
	*x = KickRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_grpcrcon_grpcrcon_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KickRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KickRequest) ProtoMessage() {}

func (x *KickRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_grpcrcon_grpcrcon_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KickRequest.ProtoReflect.Descriptor instead.
func (*KickRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_grpcrcon_grpcrcon_proto_rawDescGZIP(), []int{3}
}

func (x *KickRequest) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

func (x *KickRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *KickRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type AnnounceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServerName string `protobuf:"bytes,1,opt,name=serverName,proto3" json:"serverName,omitempty"`
	Announce   string `protobuf:"bytes,2,opt,name=announce,proto3" json:"announce,omitempty"`
}

func (x *AnnounceRequest) Reset() {
	*x = AnnounceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_grpcrcon_grpcrcon_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AnnounceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnnounceRequest) ProtoMessage() {}

func (x *AnnounceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_grpcrcon_grpcrcon_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnnounceRequest.ProtoReflect.Descriptor instead.
func (*AnnounceRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_grpcrcon_grpcrcon_proto_rawDescGZIP(), []int{4}
}

func (x *AnnounceRequest) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

func (x *AnnounceRequest) GetAnnounce() string {
	if x != nil {
		return x.Announce
	}
	return ""
}

type CommandRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServerName string `protobuf:"bytes,1,opt,name=serverName,proto3" json:"serverName,omitempty"`
	Command    string `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
}

func (x *CommandRequest) Reset() {
	*x = CommandRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_grpcrcon_grpcrcon_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandRequest) ProtoMessage() {}

func (x *CommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_grpcrcon_grpcrcon_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandRequest.ProtoReflect.Descriptor instead.
func (*CommandRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_grpcrcon_grpcrcon_proto_rawDescGZIP(), []int{5}
}

func (x *CommandRequest) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

func (x *CommandRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

type StatusResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status     ResponseStatus `protobuf:"varint,1,opt,name=status,proto3,enum=grpcrcon.ResponseStatus" json:"status,omitempty"`
	Message    string         `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	ServerName string         `protobuf:"bytes,3,opt,name=serverName,proto3" json:"serverName,omitempty"`
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_grpcrcon_grpcrcon_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_grpcrcon_grpcrcon_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_grpcrcon_grpcrcon_proto_rawDescGZIP(), []int{6}
}

func (x *StatusResponse) GetStatus() ResponseStatus {
	if x != nil {
		return x.Status
	}
	return ResponseStatus_ERROR
}

func (x *StatusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *StatusResponse) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

type RestartRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServerName   string  `protobuf:"bytes,1,opt,name=serverName,proto3" json:"serverName,omitempty"`
	Now          bool    `protobuf:"varint,2,opt,name=now,proto3" json:"now,omitempty"`
	Nolock       bool    `protobuf:"varint,3,opt,name=nolock,proto3" json:"nolock,omitempty"`
	KickHoldTime float32 `protobuf:"fixed32,4,opt,name=kickHoldTime,proto3" json:"kickHoldTime,omitempty"`
}

func (x *RestartRequest) Reset() {
	*x = RestartRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_grpcrcon_grpcrcon_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RestartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestartRequest) ProtoMessage() {}

func (x *RestartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_grpcrcon_grpcrcon_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestartRequest.ProtoReflect.Descriptor instead.
func (*RestartRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_grpcrcon_grpcrcon_proto_rawDescGZIP(), []int{7}
}

func (x *RestartRequest) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

func (x *RestartRequest) GetNow() bool {
	if x != nil {
		return x.Now
	}
	return false
}

func (x *RestartRequest) GetNolock() bool {
	if x != nil {
		return x.Nolock
	}
	return false
}

func (x *RestartRequest) GetKickHoldTime() float32 {
	if x != nil {
		return x.KickHoldTime
	}
	return 0
}

type RestartResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status     ResponseStatus `protobuf:"varint,1,opt,name=status,proto3,enum=grpcrcon.ResponseStatus" json:"status,omitempty"`
	Message    string         `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	ServerName string         `protobuf:"bytes,3,opt,name=serverName,proto3" json:"serverName,omitempty"`
}

func (x *RestartResponse) Reset() {
	*x = RestartResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_grpcrcon_grpcrcon_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RestartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestartResponse) ProtoMessage() {}

func (x *RestartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_grpcrcon_grpcrcon_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestartResponse.ProtoReflect.Descriptor instead.
func (*RestartResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_grpcrcon_grpcrcon_proto_rawDescGZIP(), []int{8}
}

func (x *RestartResponse) GetStatus() ResponseStatus {
	if x != nil {
		return x.Status
	}
	return ResponseStatus_ERROR
}

func (x *RestartResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RestartResponse) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

type ServersRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *ServersRequest) Reset() {
	*x = ServersRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_grpcrcon_grpcrcon_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServersRequest) ProtoMessage() {}

func (x *ServersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_grpcrcon_grpcrcon_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServersRequest.ProtoReflect.Descriptor instead.
func (*ServersRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_grpcrcon_grpcrcon_proto_rawDescGZIP(), []int{9}
}

func (x *ServersRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ServersResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Greeting string                          `protobuf:"bytes,1,opt,name=greeting,proto3" json:"greeting,omitempty"`
	Servers  []*ServersResponse_ServerConfig `protobuf:"bytes,2,rep,name=servers,proto3" json:"servers,omitempty"`
}

func (x *ServersResponse) Reset() {
	*x = ServersResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_grpcrcon_grpcrcon_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServersResponse) ProtoMessage() {}

func (x *ServersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_grpcrcon_grpcrcon_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServersResponse.ProtoReflect.Descriptor instead.
func (*ServersResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_grpcrcon_grpcrcon_proto_rawDescGZIP(), []int{10}
}

func (x *ServersResponse) GetGreeting() string {
	if x != nil {
		return x.Greeting
	}
	return ""
}

func (x *ServersResponse) GetServers() []*ServersResponse_ServerConfig {
	if x != nil {
		return x.Servers
	}
	return nil
}

type ServersResponse_Announcements struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	At  string `protobuf:"bytes,1,opt,name=at,proto3" json:"at,omitempty"`
	Min string `protobuf:"bytes,2,opt,name=min,proto3" json:"min,omitempty"`
	Sec string `protobuf:"bytes,3,opt,name=sec,proto3" json:"sec,omitempty"`
}

func (x *ServersResponse_Announcements) Reset() {
	*x = ServersResponse_Announcements{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_grpcrcon_grpcrcon_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServersResponse_Announcements) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServersResponse_Announcements) ProtoMessage() {}

func (x *ServersResponse_Announcements) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_grpcrcon_grpcrcon_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServersResponse_Announcements.ProtoReflect.Descriptor instead.
func (*ServersResponse_Announcements) Descriptor() ([]byte, []int) {
	return file_internal_proto_grpcrcon_grpcrcon_proto_rawDescGZIP(), []int{10, 0}
}

func (x *ServersResponse_Announcements) GetAt() string {
	if x != nil {
		return x.At
	}
	return ""
}

func (x *ServersResponse_Announcements) GetMin() string {
	if x != nil {
		return x.Min
	}
	return ""
}

func (x *ServersResponse_Announcements) GetSec() string {
	if x != nil {
		return x.Sec
	}
	return ""
}

type ServersResponse_RestartConf struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Period        int64                          `protobuf:"varint,1,opt,name=period,proto3" json:"period,omitempty"`
	ServerLock    int64                          `protobuf:"varint,2,opt,name=serverLock,proto3" json:"serverLock,omitempty"`
	Announcements *ServersResponse_Announcements `protobuf:"bytes,3,opt,name=announcements,proto3" json:"announcements,omitempty"`
}

func (x *ServersResponse_RestartConf) Reset() {
	*x = ServersResponse_RestartConf{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_grpcrcon_grpcrcon_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServersResponse_RestartConf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServersResponse_RestartConf) ProtoMessage() {}

func (x *ServersResponse_RestartConf) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_grpcrcon_grpcrcon_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServersResponse_RestartConf.ProtoReflect.Descriptor instead.
func (*ServersResponse_RestartConf) Descriptor() ([]byte, []int) {
	return file_internal_proto_grpcrcon_grpcrcon_proto_rawDescGZIP(), []int{10, 1}
}

func (x *ServersResponse_RestartConf) GetPeriod() int64 {
	if x != nil {
		return x.Period
	}
	return 0
}

func (x *ServersResponse_RestartConf) GetServerLock() int64 {
	if x != nil {
		return x.ServerLock
	}
	return 0
}

func (x *ServersResponse_RestartConf) GetAnnouncements() *ServersResponse_Announcements {
	if x != nil {
		return x.Announcements
	}
	return nil
}

type ServersResponse_ServerConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string                       `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Host        string                       `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Port        int32                        `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	Password    string                       `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	RestartConf *ServersResponse_RestartConf `protobuf:"bytes,5,opt,name=restartConf,proto3" json:"restartConf,omitempty"`
}

func (x *ServersResponse_ServerConfig) Reset() {
	*x = ServersResponse_ServerConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_grpcrcon_grpcrcon_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServersResponse_ServerConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServersResponse_ServerConfig) ProtoMessage() {}

func (x *ServersResponse_ServerConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_grpcrcon_grpcrcon_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServersResponse_ServerConfig.ProtoReflect.Descriptor instead.
func (*ServersResponse_ServerConfig) Descriptor() ([]byte, []int) {
	return file_internal_proto_grpcrcon_grpcrcon_proto_rawDescGZIP(), []int{10, 2}
}

func (x *ServersResponse_ServerConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServersResponse_ServerConfig) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *ServersResponse_ServerConfig) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *ServersResponse_ServerConfig) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *ServersResponse_ServerConfig) GetRestartConf() *ServersResponse_RestartConf {
	if x != nil {
		return x.RestartConf
	}
	return nil
}

var File_internal_proto_grpcrcon_grpcrcon_proto protoreflect.FileDescriptor

var file_internal_proto_grpcrcon_grpcrcon_proto_rawDesc = []byte{
	0x0a, 0x26, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x67, 0x72, 0x70, 0x63, 0x72, 0x63, 0x6f, 0x6e, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x72, 0x63,
	0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x67, 0x72, 0x70, 0x63, 0x72, 0x63,
	0x6f, 0x6e, 0x22, 0x2d, 0x0a, 0x0b, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4e, 0x61, 0x6d,
	0x65, 0x22, 0x2f, 0x0a, 0x0d, 0x75, 0x6e, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4e, 0x61,
	0x6d, 0x65, 0x22, 0x31, 0x0a, 0x0f, 0x73, 0x68, 0x75, 0x74, 0x64, 0x6f, 0x77, 0x6e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x63, 0x0a, 0x0b, 0x6b, 0x69, 0x63, 0x6b, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64,
	0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x4d, 0x0a, 0x0f, 0x61, 0x6e,
	0x6e, 0x6f, 0x75, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a,
	0x0a, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a,
	0x08, 0x61, 0x6e, 0x6e, 0x6f, 0x75, 0x6e, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x61, 0x6e, 0x6e, 0x6f, 0x75, 0x6e, 0x63, 0x65, 0x22, 0x4a, 0x0a, 0x0e, 0x63, 0x6f, 0x6d,
	0x6d, 0x61, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63,
	0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f,
	0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x22, 0x7c, 0x0a, 0x0e, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x30, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x18, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x72, 0x63,
	0x6f, 0x6e, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4e, 0x61, 0x6d,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4e,
	0x61, 0x6d, 0x65, 0x22, 0x7e, 0x0a, 0x0e, 0x72, 0x65, 0x73, 0x74, 0x61, 0x72, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6e, 0x6f, 0x77, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x03, 0x6e, 0x6f, 0x77, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x6f, 0x6c, 0x6f, 0x63,
	0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x6e, 0x6f, 0x6c, 0x6f, 0x63, 0x6b, 0x12,
	0x22, 0x0a, 0x0c, 0x6b, 0x69, 0x63, 0x6b, 0x48, 0x6f, 0x6c, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0c, 0x6b, 0x69, 0x63, 0x6b, 0x48, 0x6f, 0x6c, 0x64, 0x54,
	0x69, 0x6d, 0x65, 0x22, 0x7d, 0x0a, 0x0f, 0x72, 0x65, 0x73, 0x74, 0x61, 0x72, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x30, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x18, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x72, 0x63, 0x6f,
	0x6e, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4e, 0x61,
	0x6d, 0x65, 0x22, 0x24, 0x0a, 0x0e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0xfd, 0x03, 0x0a, 0x0f, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08,
	0x67, 0x72, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x67, 0x72, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x12, 0x40, 0x0a, 0x07, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x67, 0x72, 0x70, 0x63,
	0x72, 0x63, 0x6f, 0x6e, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x52, 0x07, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x73, 0x1a, 0x43, 0x0a, 0x0d, 0x41, 0x6e,
	0x6e, 0x6f, 0x75, 0x6e, 0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x61,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x61, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6d,
	0x69, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x69, 0x6e, 0x12, 0x10, 0x0a,
	0x03, 0x73, 0x65, 0x63, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x73, 0x65, 0x63, 0x1a,
	0x94, 0x01, 0x0a, 0x0b, 0x52, 0x65, 0x73, 0x74, 0x61, 0x72, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x12,
	0x16, 0x0a, 0x06, 0x70, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x06, 0x70, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x4c, 0x6f, 0x63, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x4c, 0x6f, 0x63, 0x6b, 0x12, 0x4d, 0x0a, 0x0d, 0x61, 0x6e, 0x6e, 0x6f, 0x75,
	0x6e, 0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x27,
	0x2e, 0x67, 0x72, 0x70, 0x63, 0x72, 0x63, 0x6f, 0x6e, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x41, 0x6e, 0x6e, 0x6f, 0x75, 0x6e,
	0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x0d, 0x61, 0x6e, 0x6e, 0x6f, 0x75, 0x6e, 0x63,
	0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x1a, 0xaf, 0x01, 0x0a, 0x0c, 0x53, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x68,
	0x6f, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70,
	0x6f, 0x72, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12,
	0x47, 0x0a, 0x0b, 0x72, 0x65, 0x73, 0x74, 0x61, 0x72, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x72, 0x63, 0x6f, 0x6e, 0x2e,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e,
	0x52, 0x65, 0x73, 0x74, 0x61, 0x72, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x52, 0x0b, 0x72, 0x65, 0x73,
	0x74, 0x61, 0x72, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x2a, 0x28, 0x0a, 0x0e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x09, 0x0a, 0x05, 0x45, 0x52,
	0x52, 0x4f, 0x52, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x55, 0x43, 0x43, 0x45, 0x53, 0x53,
	0x10, 0x01, 0x32, 0xb8, 0x04, 0x0a, 0x0f, 0x47, 0x52, 0x50, 0x43, 0x52, 0x43, 0x4f, 0x4e, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3e, 0x0a, 0x07, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x73, 0x12, 0x18, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x72, 0x63, 0x6f, 0x6e, 0x2e, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x67, 0x72,
	0x70, 0x63, 0x72, 0x63, 0x6f, 0x6e, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3d, 0x0a, 0x07, 0x52, 0x65, 0x73, 0x74, 0x61, 0x72,
	0x74, 0x12, 0x18, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x72, 0x63, 0x6f, 0x6e, 0x2e, 0x72, 0x65, 0x73,
	0x74, 0x61, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x67, 0x72,
	0x70, 0x63, 0x72, 0x63, 0x6f, 0x6e, 0x2e, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3d, 0x0a, 0x07, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64,
	0x12, 0x18, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x72, 0x63, 0x6f, 0x6e, 0x2e, 0x63, 0x6f, 0x6d, 0x6d,
	0x61, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x67, 0x72, 0x70,
	0x63, 0x72, 0x63, 0x6f, 0x6e, 0x2e, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3f, 0x0a, 0x08, 0x41, 0x6e, 0x6e, 0x6f, 0x75, 0x6e, 0x63, 0x65,
	0x12, 0x19, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x72, 0x63, 0x6f, 0x6e, 0x2e, 0x61, 0x6e, 0x6e, 0x6f,
	0x75, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x67, 0x72,
	0x70, 0x63, 0x72, 0x63, 0x6f, 0x6e, 0x2e, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x37, 0x0a, 0x04, 0x4b, 0x69, 0x63, 0x6b, 0x12, 0x15, 0x2e,
	0x67, 0x72, 0x70, 0x63, 0x72, 0x63, 0x6f, 0x6e, 0x2e, 0x6b, 0x69, 0x63, 0x6b, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x72, 0x63, 0x6f, 0x6e, 0x2e,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x37,
	0x0a, 0x04, 0x4c, 0x6f, 0x63, 0x6b, 0x12, 0x15, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x72, 0x63, 0x6f,
	0x6e, 0x2e, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e,
	0x67, 0x72, 0x70, 0x63, 0x72, 0x63, 0x6f, 0x6e, 0x2e, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x36, 0x0a, 0x03, 0x53, 0x61, 0x79, 0x12, 0x15,
	0x2e, 0x67, 0x72, 0x70, 0x63, 0x72, 0x63, 0x6f, 0x6e, 0x2e, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x72, 0x63, 0x6f, 0x6e,
	0x2e, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x3f, 0x0a, 0x08, 0x53, 0x68, 0x75, 0x74, 0x64, 0x6f, 0x77, 0x6e, 0x12, 0x19, 0x2e, 0x67, 0x72,
	0x70, 0x63, 0x72, 0x63, 0x6f, 0x6e, 0x2e, 0x73, 0x68, 0x75, 0x74, 0x64, 0x6f, 0x77, 0x6e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x72, 0x63, 0x6f,
	0x6e, 0x2e, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x3b, 0x0a, 0x06, 0x55, 0x6e, 0x6c, 0x6f, 0x63, 0x6b, 0x12, 0x17, 0x2e, 0x67, 0x72, 0x70,
	0x63, 0x72, 0x63, 0x6f, 0x6e, 0x2e, 0x75, 0x6e, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x72, 0x63, 0x6f, 0x6e, 0x2e, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x3f, 0x5a,
	0x3d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x69, 0x6b, 0x30,
	0x2d, 0x6f, 0x2f, 0x67, 0x6f, 0x72, 0x63, 0x6f, 0x6e, 0x2d, 0x72, 0x65, 0x73, 0x74, 0x61, 0x72,
	0x74, 0x65, 0x72, 0x2f, 0x76, 0x32, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x72, 0x63, 0x6f, 0x6e, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_proto_grpcrcon_grpcrcon_proto_rawDescOnce sync.Once
	file_internal_proto_grpcrcon_grpcrcon_proto_rawDescData = file_internal_proto_grpcrcon_grpcrcon_proto_rawDesc
)

func file_internal_proto_grpcrcon_grpcrcon_proto_rawDescGZIP() []byte {
	file_internal_proto_grpcrcon_grpcrcon_proto_rawDescOnce.Do(func() {
		file_internal_proto_grpcrcon_grpcrcon_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_proto_grpcrcon_grpcrcon_proto_rawDescData)
	})
	return file_internal_proto_grpcrcon_grpcrcon_proto_rawDescData
}

var file_internal_proto_grpcrcon_grpcrcon_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_proto_grpcrcon_grpcrcon_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_internal_proto_grpcrcon_grpcrcon_proto_goTypes = []interface{}{
	(ResponseStatus)(0),                   // 0: grpcrcon.ResponseStatus
	(*LockRequest)(nil),                   // 1: grpcrcon.lockRequest
	(*UnlockRequest)(nil),                 // 2: grpcrcon.unlockRequest
	(*ShutdownRequest)(nil),               // 3: grpcrcon.shutdownRequest
	(*KickRequest)(nil),                   // 4: grpcrcon.kickRequest
	(*AnnounceRequest)(nil),               // 5: grpcrcon.announceRequest
	(*CommandRequest)(nil),                // 6: grpcrcon.commandRequest
	(*StatusResponse)(nil),                // 7: grpcrcon.statusResponse
	(*RestartRequest)(nil),                // 8: grpcrcon.restartRequest
	(*RestartResponse)(nil),               // 9: grpcrcon.restartResponse
	(*ServersRequest)(nil),                // 10: grpcrcon.serversRequest
	(*ServersResponse)(nil),               // 11: grpcrcon.serversResponse
	(*ServersResponse_Announcements)(nil), // 12: grpcrcon.serversResponse.Announcements
	(*ServersResponse_RestartConf)(nil),   // 13: grpcrcon.serversResponse.RestartConf
	(*ServersResponse_ServerConfig)(nil),  // 14: grpcrcon.serversResponse.ServerConfig
}
var file_internal_proto_grpcrcon_grpcrcon_proto_depIdxs = []int32{
	0,  // 0: grpcrcon.statusResponse.status:type_name -> grpcrcon.ResponseStatus
	0,  // 1: grpcrcon.restartResponse.status:type_name -> grpcrcon.ResponseStatus
	14, // 2: grpcrcon.serversResponse.servers:type_name -> grpcrcon.serversResponse.ServerConfig
	12, // 3: grpcrcon.serversResponse.RestartConf.announcements:type_name -> grpcrcon.serversResponse.Announcements
	13, // 4: grpcrcon.serversResponse.ServerConfig.restartConf:type_name -> grpcrcon.serversResponse.RestartConf
	10, // 5: grpcrcon.GRPCRCONService.Servers:input_type -> grpcrcon.serversRequest
	8,  // 6: grpcrcon.GRPCRCONService.Restart:input_type -> grpcrcon.restartRequest
	6,  // 7: grpcrcon.GRPCRCONService.Command:input_type -> grpcrcon.commandRequest
	5,  // 8: grpcrcon.GRPCRCONService.Announce:input_type -> grpcrcon.announceRequest
	4,  // 9: grpcrcon.GRPCRCONService.Kick:input_type -> grpcrcon.kickRequest
	1,  // 10: grpcrcon.GRPCRCONService.Lock:input_type -> grpcrcon.lockRequest
	1,  // 11: grpcrcon.GRPCRCONService.Say:input_type -> grpcrcon.lockRequest
	3,  // 12: grpcrcon.GRPCRCONService.Shutdown:input_type -> grpcrcon.shutdownRequest
	2,  // 13: grpcrcon.GRPCRCONService.Unlock:input_type -> grpcrcon.unlockRequest
	11, // 14: grpcrcon.GRPCRCONService.Servers:output_type -> grpcrcon.serversResponse
	7,  // 15: grpcrcon.GRPCRCONService.Restart:output_type -> grpcrcon.statusResponse
	7,  // 16: grpcrcon.GRPCRCONService.Command:output_type -> grpcrcon.statusResponse
	7,  // 17: grpcrcon.GRPCRCONService.Announce:output_type -> grpcrcon.statusResponse
	7,  // 18: grpcrcon.GRPCRCONService.Kick:output_type -> grpcrcon.statusResponse
	7,  // 19: grpcrcon.GRPCRCONService.Lock:output_type -> grpcrcon.statusResponse
	7,  // 20: grpcrcon.GRPCRCONService.Say:output_type -> grpcrcon.statusResponse
	7,  // 21: grpcrcon.GRPCRCONService.Shutdown:output_type -> grpcrcon.statusResponse
	7,  // 22: grpcrcon.GRPCRCONService.Unlock:output_type -> grpcrcon.statusResponse
	14, // [14:23] is the sub-list for method output_type
	5,  // [5:14] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_internal_proto_grpcrcon_grpcrcon_proto_init() }
func file_internal_proto_grpcrcon_grpcrcon_proto_init() {
	if File_internal_proto_grpcrcon_grpcrcon_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_proto_grpcrcon_grpcrcon_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LockRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_grpcrcon_grpcrcon_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnlockRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_grpcrcon_grpcrcon_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShutdownRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_grpcrcon_grpcrcon_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KickRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_grpcrcon_grpcrcon_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AnnounceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_grpcrcon_grpcrcon_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommandRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_grpcrcon_grpcrcon_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatusResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_grpcrcon_grpcrcon_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RestartRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_grpcrcon_grpcrcon_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RestartResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_grpcrcon_grpcrcon_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServersRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_grpcrcon_grpcrcon_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServersResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_grpcrcon_grpcrcon_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServersResponse_Announcements); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_grpcrcon_grpcrcon_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServersResponse_RestartConf); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_grpcrcon_grpcrcon_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServersResponse_ServerConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_proto_grpcrcon_grpcrcon_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_grpcrcon_grpcrcon_proto_goTypes,
		DependencyIndexes: file_internal_proto_grpcrcon_grpcrcon_proto_depIdxs,
		EnumInfos:         file_internal_proto_grpcrcon_grpcrcon_proto_enumTypes,
		MessageInfos:      file_internal_proto_grpcrcon_grpcrcon_proto_msgTypes,
	}.Build()
	File_internal_proto_grpcrcon_grpcrcon_proto = out.File
	file_internal_proto_grpcrcon_grpcrcon_proto_rawDesc = nil
	file_internal_proto_grpcrcon_grpcrcon_proto_goTypes = nil
	file_internal_proto_grpcrcon_grpcrcon_proto_depIdxs = nil
}
